spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/test01
    username: beres
    password: beres
debug: true

metadata:
  pdf:  "dcterms:created"
  docx: "dcterms:created"
  jpg:  "Exif SubIFD:Date/Time Original"
  nef:  "Exif SubIFD:Date/Time Original"