# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    name: Deploy with Maven

    # runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Use Command Prompt to ENV
      shell: cmd
      run: 
        echo PATH = "$env.PATH"
        echo JAVA_HOME = "$env.JAVA_HOME"
        echo MAVEN_HOME = "$env.MAVEN_HOME"
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Publish package
      run: mvn --settings "$env:USERPROFILE\.github\workflows\settings.xml" --batch-mode -e -X deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
